package net.unitedcloud

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {

    def filters = {

//        anonymous(controller: "simpleCaptcha", action: "captcha"){
//            before={
//                print ("simpleCaptcha OK")
////                accessControl(auth: false)
////                accessControl{
////                    permission("*:*")
////                }
//            }
//            after ={
//                print ("simpleCaptcha ShiroSecurityFilters after")
//
//                return true
//            }
//        }

        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

//                println request.requestURI

                if(controllerName == "simpleCaptcha") return true
                // Access control by convention.
                accessControl(auth:false)
            }
        }

        management(controller: "shiroRole|shiroUser", action: "*"){
            before={
                accessControl{
                    role("Admin")
                }
            }
        }
//
//        user(controller: "shiroUser", action: "update"){
//            before={
//                accessControl{
//                    permission("shiroUser:update:$params.id")
//                }
//            }
//        }

    }
}
